/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import com.ijse.sss.connector.ServerConnector;
import com.ijse.sss.controller.NoteController;
import com.ijse.sss.controller.QuestionController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import com.ijse.sss.model.Question;

/**
 *
 * @author NEOx
 */
public class ChangeQuestion extends javax.swing.JFrame {

    /**
     * Creates new form ChangeQuestion
     */
    private int count = 1;
    private TeacherMain teacherMain;
    private ArrayList<Question> readQuestionsModule;
    private String changingQid;

    public ChangeQuestion(TeacherMain teacherMain) {
        initComponents();
        this.teacherMain = teacherMain;
        autoDateTime();
        addModules();
    }

    private void autoDateTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    Date date = new Date();
                    String curTime = new SimpleDateFormat("hh:mm aa").format(time);
                    String curDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
                    lblTime.setText(curTime);
                    lblDate.setText(curDate);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void addModules() {
        try {
            DefaultListModel<String> defaultListModel = new DefaultListModel<>();
            lstModule.setModel(defaultListModel);
            defaultListModel.removeAllElements();
            QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
            ArrayList<String> module = questionController.getAllQuestionModules();
            for (String string : module) {
                defaultListModel.addElement(string);
                cbModule.addItem(string);
            }

            btBack.setVisible(false);

        } catch (RemoteException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblModule8 = new javax.swing.JLabel();
        lblModule9 = new javax.swing.JLabel();
        lblModule10 = new javax.swing.JLabel();
        lblModule11 = new javax.swing.JLabel();
        lblModule7 = new javax.swing.JLabel();
        lblModule3 = new javax.swing.JLabel();
        lblModule4 = new javax.swing.JLabel();
        lblModule5 = new javax.swing.JLabel();
        lblModule6 = new javax.swing.JLabel();
        lblModule2 = new javax.swing.JLabel();
        txtAns3 = new javax.swing.JTextField();
        txtAns2 = new javax.swing.JTextField();
        txtCorrectAns = new javax.swing.JTextField();
        txtAns1 = new javax.swing.JTextField();
        btBack1 = new javax.swing.JButton();
        cbModule = new javax.swing.JComboBox<>();
        lblModule1 = new javax.swing.JLabel();
        btBackToNote = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        lblModule = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstModule = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModule8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule8.setForeground(new java.awt.Color(255, 255, 255));
        lblModule8.setText(":");
        jPanel7.add(lblModule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 30, 60));

        lblModule9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule9.setForeground(new java.awt.Color(255, 255, 255));
        lblModule9.setText(":");
        jPanel7.add(lblModule9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 30, 60));

        lblModule10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule10.setForeground(new java.awt.Color(255, 255, 255));
        lblModule10.setText(":");
        jPanel7.add(lblModule10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 30, 60));

        lblModule11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule11.setForeground(new java.awt.Color(255, 255, 255));
        lblModule11.setText(":");
        jPanel7.add(lblModule11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 650, 30, 60));

        lblModule7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule7.setForeground(new java.awt.Color(255, 255, 255));
        lblModule7.setText(":");
        jPanel7.add(lblModule7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 30, 60));

        lblModule3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule3.setForeground(new java.awt.Color(255, 255, 255));
        lblModule3.setText("Answer 1");
        jPanel7.add(lblModule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 180, 60));

        lblModule4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule4.setForeground(new java.awt.Color(255, 255, 255));
        lblModule4.setText("Answer 3");
        jPanel7.add(lblModule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 740, 180, 60));

        lblModule5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule5.setForeground(new java.awt.Color(255, 255, 255));
        lblModule5.setText("Answer 2");
        jPanel7.add(lblModule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, 180, 60));

        lblModule6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule6.setForeground(new java.awt.Color(255, 255, 255));
        lblModule6.setText("Correct Answer");
        jPanel7.add(lblModule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 260, 60));

        lblModule2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule2.setForeground(new java.awt.Color(255, 255, 255));
        lblModule2.setText("Question");
        jPanel7.add(lblModule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 180, 60));

        txtAns3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
        txtAns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAns3ActionPerformed(evt);
            }
        });
        jPanel7.add(txtAns3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 740, 550, 50));

        txtAns2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
        txtAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAns2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtAns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 650, 550, 50));

        txtCorrectAns.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
        txtCorrectAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorrectAnsActionPerformed(evt);
            }
        });
        jPanel7.add(txtCorrectAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 550, 50));

        txtAns1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
        txtAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAns1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtAns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 550, 50));

        btBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/changebtSmall.jpg"))); // NOI18N
        btBack1.setEnabled(false);
        btBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBack1MousePressed(evt);
            }
        });
        btBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack1ActionPerformed(evt);
            }
        });
        jPanel7.add(btBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 960, 160, 60));

        cbModule.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel7.add(cbModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 970, 470, 50));

        lblModule1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblModule1.setForeground(new java.awt.Color(255, 255, 255));
        lblModule1.setText("Module  :");
        jPanel7.add(lblModule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 970, 180, 60));

        btBackToNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/btBackToQuestions.jpg"))); // NOI18N
        btBackToNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBackToNoteMousePressed(evt);
            }
        });
        btBackToNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackToNoteActionPerformed(evt);
            }
        });
        jPanel7.add(btBackToNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 960, 290, 60));

        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/backbt.jpg"))); // NOI18N
        btBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBackMousePressed(evt);
            }
        });
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel7.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 950, 160, 70));

        txtQuestion.setColumns(20);
        txtQuestion.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 890, 190));

        lblModule.setFont(new java.awt.Font("Microsoft Himalaya", 1, 70)); // NOI18N
        lblModule.setForeground(new java.awt.Color(255, 255, 255));
        lblModule.setText("Modules");
        jPanel7.add(lblModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 240, 60));

        lstModule.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lstModule.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstModuleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lstModuleMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstModuleMousePressed(evt);
            }
        });
        lstModule.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstModuleValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstModule);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 550, 640));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHANGE QUESTIONS");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 860, 110));

        lblTime.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("08:00");
        jPanel7.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 50, 330, 90));

        lblDate.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("08:00");
        jPanel7.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 120, 310, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 950, 1260, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 950, 1260, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 590, 820));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 590, 820));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 1260, 730));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 1260, 730));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/white transparent.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1000));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1880, 1020));

        lblBackgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/technology-1106438_960_720darky.jpg"))); // NOI18N
        jPanel7.add(lblBackgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBack1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBack1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBack1MousePressed

    private void btBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack1ActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Are You Sure You want to Change..??");
        if (res == 0) {
            String newQuestion = txtQuestion.getText();
            String newCorrectAnswer = txtCorrectAns.getText();
            String newAns1 = txtAns1.getText();
            String newAns2 = txtAns2.getText();
            String newAns3 = txtAns3.getText();
            String newModule = (String) cbModule.getSelectedItem();

            if (!newQuestion.equals("") && !newCorrectAnswer.equals("") && !newAns1.equals("") && !newAns2.equals("") && !newAns3.equals("")) {
                Question question = new Question(changingQid, newQuestion, newCorrectAnswer, newAns1, newAns2, newAns3, newModule);

                try {
                    QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
                    boolean isUpdate = questionController.updateQuestion(question);

                    if (isUpdate) {
                        JOptionPane.showMessageDialog(this, "Question Updated Successfully....");
                        questionController.releaseQuestion(this.changingQid);
                        new QuestionsForm(teacherMain).setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Question Updation Failed....");
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Fill all the Fields....");
            }
        }
    }//GEN-LAST:event_btBack1ActionPerformed

    private void btBackToNoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackToNoteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBackToNoteMousePressed

    private void btBackToNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackToNoteActionPerformed
        try {
            QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
            questionController.releaseQuestion(this.changingQid);
            new QuestionsForm(teacherMain).setVisible(true);
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBackToNoteActionPerformed

    private void btBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBackMousePressed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        addModules();
        lblModule.setText("Modules");
        count = 1;
        btBack.setVisible(false);
    }//GEN-LAST:event_btBackActionPerformed

    private void lstModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstModuleMouseClicked
        if (count == 1) {
            String module = lstModule.getSelectedValue();
            addQuestions(module);
            btBack.setVisible(true);
            lblModule.setText("Topics");
            count = 2;
        } else if (count == 2) {
            String topic = lstModule.getSelectedValue();
            previewQuestion();
        }
    }//GEN-LAST:event_lstModuleMouseClicked

    private void lstModuleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstModuleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lstModuleMouseEntered

    private void lstModuleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstModuleMousePressed

    }//GEN-LAST:event_lstModuleMousePressed

    private void lstModuleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstModuleValueChanged

    }//GEN-LAST:event_lstModuleValueChanged

    private void txtAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAns2ActionPerformed
        txtAns1.requestFocus();
    }//GEN-LAST:event_txtAns2ActionPerformed

    private void txtCorrectAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorrectAnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrectAnsActionPerformed

    private void txtAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAns1ActionPerformed

    private void txtAns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAns3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAns3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBack1;
    private javax.swing.JButton btBackToNote;
    private javax.swing.JComboBox<String> cbModule;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackgrond;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblModule1;
    private javax.swing.JLabel lblModule10;
    private javax.swing.JLabel lblModule11;
    private javax.swing.JLabel lblModule2;
    private javax.swing.JLabel lblModule3;
    private javax.swing.JLabel lblModule4;
    private javax.swing.JLabel lblModule5;
    private javax.swing.JLabel lblModule6;
    private javax.swing.JLabel lblModule7;
    private javax.swing.JLabel lblModule8;
    private javax.swing.JLabel lblModule9;
    private javax.swing.JLabel lblTime;
    private javax.swing.JList<String> lstModule;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns2;
    private javax.swing.JTextField txtAns3;
    private javax.swing.JTextField txtCorrectAns;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
    private void addQuestions(String module) {
        try {
            DefaultListModel<String> defaultListModel = new DefaultListModel<>();
            lstModule.setModel(defaultListModel);
            defaultListModel.removeAllElements();
            QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
            this.readQuestionsModule = questionController.readQuestionsModule(module);

            for (Question question : readQuestionsModule) {
                defaultListModel.addElement(question.getQuestion());
            }

        } catch (RemoteException ex) {
            Logger.getLogger(ChangeNotes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException | MalformedURLException ex) {
            Logger.getLogger(ChangeNotes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangeNotes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void previewQuestion() {
        String selectedValue = lstModule.getSelectedValue();
        String changingQid;
        for (Question question : readQuestionsModule) {
            if (selectedValue.equals(question.getQuestion())) {
                try {
                    QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
                    changingQid = question.getQid();

                    if (this.changingQid != changingQid) {
                        questionController.releaseQuestion(this.changingQid);
                    }
                    this.changingQid = changingQid;

                    if (questionController.reserveQuestion(changingQid)) {
                        txtQuestion.setText(question.getQuestion());
                        txtCorrectAns.setText(question.getCorrectAnswer());
                        txtAns1.setText(question.getAnswer1());
                        txtAns2.setText(question.getAnswer2());
                        txtAns3.setText(question.getAnswer3());
                        cbModule.setSelectedItem(question.getModule());
                        btBack1.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "This Question is already Reserved....");
                    }

                } catch (RemoteException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChangeQuestion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

}
