/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import com.ijse.sss.connector.ServerConnector;
import com.ijse.sss.controller.NoteController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author NEOx
 */
public class NotesForm extends javax.swing.JFrame {

    /**
     * Creates new form NotesForm
     */
    private TeacherMain teacherMain;

    public NotesForm(TeacherMain teacherMain) {
        initComponents();
        this.teacherMain = teacherMain;
        autoDateTime();
        addTopics();
    }

    private void autoDateTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    Date date = new Date();
                    String curTime = new SimpleDateFormat("hh:mm aa").format(time);
                    String curDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
                    lblTime.setText(curTime);
                    lblDate.setText(curDate);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(CreateNewTeacher.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void addTopics() {
        try {
            DefaultListModel<String> defaultListModel = new DefaultListModel<>();
            lstTopics.setModel(defaultListModel);
            defaultListModel.removeAllElements();
            NoteController noteController = ServerConnector.getServerConnector().getNoteController();
            ArrayList<String> topics = noteController.getAllTopics();
            if (topics != null) {
                for (String topic : topics) {
                    defaultListModel.addElement(topic);
                }
            }

        } catch (RemoteException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(NotesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btView = new javax.swing.JButton();
        btBackToNote = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTopics = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btChange = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/viewNotes.jpg"))); // NOI18N
        btView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btViewMouseExited(evt);
            }
        });
        btView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewActionPerformed(evt);
            }
        });
        jPanel5.add(btView, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, 390, 340));

        btBackToNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/btBackToHome.jpg"))); // NOI18N
        btBackToNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBackToNoteMousePressed(evt);
            }
        });
        btBackToNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackToNoteActionPerformed(evt);
            }
        });
        jPanel5.add(btBackToNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 960, 290, 60));

        lstTopics.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lstTopics.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstTopics);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 310, 620, 630));

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Existing Notes");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 230, 430, 90));

        btChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/changeNotesbt.jpg"))); // NOI18N
        btChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btChangeMouseExited(evt);
            }
        });
        btChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeActionPerformed(evt);
            }
        });
        jPanel5.add(btChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 390, 340));

        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/createNote.jpg"))); // NOI18N
        btCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCreateMouseExited(evt);
            }
        });
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        jPanel5.add(btCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 390, 340));

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/deleteNotebt.jpg"))); // NOI18N
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDeleteMouseExited(evt);
            }
        });
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 390, 340));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOTES");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 220, 90));

        lblTime.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("08:00");
        jPanel5.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 50, 330, 90));

        lblDate.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("08:00");
        jPanel5.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 120, 310, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1860, 820));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1860, 820));

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/white transparent.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1000));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1880, 1020));

        lblBackgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/technology-1106438_960_720darky.jpg"))); // NOI18N
        jPanel5.add(lblBackgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChangeMouseEntered
        btChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/changeNotesbtSel.jpg")));
    }//GEN-LAST:event_btChangeMouseEntered

    private void btChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChangeMouseExited
        btChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/changeNotesbt.jpg")));
    }//GEN-LAST:event_btChangeMouseExited

    private void btCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateMouseEntered
        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/createNoteSel.jpg")));
    }//GEN-LAST:event_btCreateMouseEntered

    private void btCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateMouseExited
        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/createNote.jpg")));
    }//GEN-LAST:event_btCreateMouseExited

    private void btDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseEntered
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/deleteNotebtSel.jpg")));
    }//GEN-LAST:event_btDeleteMouseEntered

    private void btDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseExited
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/deleteNotebt.jpg")));
    }//GEN-LAST:event_btDeleteMouseExited

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        this.dispose();
        new AddNote(teacherMain).setVisible(true);
    }//GEN-LAST:event_btCreateActionPerformed

    private void btChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeActionPerformed
        new ChangeNotes(teacherMain).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btChangeActionPerformed

    private void btBackToNoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackToNoteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBackToNoteMousePressed

    private void btBackToNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackToNoteActionPerformed
        teacherMain.show();
        this.dispose();
    }//GEN-LAST:event_btBackToNoteActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        new DeleteNotes(teacherMain).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btViewMouseEntered
        btView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/viewNotesSel.jpg")));
    }//GEN-LAST:event_btViewMouseEntered

    private void btViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btViewMouseExited
        btView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/viewNotes.jpg")));
    }//GEN-LAST:event_btViewMouseExited

    private void btViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewActionPerformed
        new ViewNotes(teacherMain).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btViewActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackToNote;
    private javax.swing.JButton btChange;
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackgrond;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JList<String> lstTopics;
    // End of variables declaration//GEN-END:variables
}
