/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import com.ijse.sss.connector.ServerConnector;
import com.ijse.sss.controller.StudentController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.ijse.sss.model.Student;
import com.ijse.sss.observer.StudentObserverImpl;
import java.text.ParseException;

/**
 *
 * @author NEOx
 */
public class CreateNewAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewAccount
     */
    private String stId;
    private String userName;
    private String stName;
    private String dob;
    private String gender;
    private String pass;
    private String conPass;
    private StudentObserverImpl studentObserverImpl;

    public CreateNewAccount() {
        initComponents();
        lblCor.setVisible(false);
        lblCorUser.setVisible(false);
        txtUserName.requestFocus();
        setExtendedState(MAXIMIZED_BOTH);
        autoDateTime();
    }

    private void autoDateTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    Date date = new Date();
                    String curTime = new SimpleDateFormat("hh:mm aa").format(time);
                    String curDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
                    lblTime.setText(curTime);
                    lblDate.setText(curDate);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public void assignStudentObserver(StudentObserverImpl studentObserverImpl) {
        this.studentObserverImpl = studentObserverImpl;
    }

    private int checkFields() {
        stId = "st1";
        userName = txtUserName.getText();
        stName = txtName.getText();
        dob = txtDOB.getText();
        
        if (JrbMale.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }
        pass = txtPass.getText();
        conPass = txtConPass.getText();

        if (userName.equals("") | stName.equals("") | pass.equals("") | conPass.equals("")) {
            if (!pass.equals(conPass)) {
                return 0;
            } else {
                return 1;
            }
        } else {
            if (!pass.equals(conPass)) {
                return 2;
            } else {
                return 3;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCorUser = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btCreateNewAccount = new javax.swing.JButton();
        chxbTurms = new javax.swing.JCheckBox();
        txtConPass = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JrbFemale = new javax.swing.JRadioButton();
        txtDOB = new datechooser.beans.DateChooserCombo();
        JrbMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorUser.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        lblCorUser.setForeground(new java.awt.Color(0, 51, 153));
        lblCorUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/1-33-512.png"))); // NOI18N
        jPanel1.add(lblCorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, 60, 60));

        lblDate.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 102, 204));
        lblDate.setText("08:00");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 120, 310, 90));

        lblTime.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 51, 255));
        lblTime.setText("08:00");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 60, 330, 90));

        lblCor.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        lblCor.setForeground(new java.awt.Color(0, 51, 153));
        lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/1-33-512.png"))); // NOI18N
        jPanel1.add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 60, 60));

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/cancelbt.jpg"))); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 900, 220, 100));

        btCreateNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/create account btA.jpg"))); // NOI18N
        btCreateNewAccount.setEnabled(false);
        btCreateNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateNewAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btCreateNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 900, 370, 100));

        chxbTurms.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        chxbTurms.setForeground(new java.awt.Color(0, 51, 255));
        chxbTurms.setText("  I Agree with the Turms and Conditions");
        chxbTurms.setOpaque(false);
        chxbTurms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxbTurmsActionPerformed(evt);
            }
        });
        jPanel1.add(chxbTurms, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 750, 900, 80));

        txtConPass.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        txtConPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConPassKeyReleased(evt);
            }
        });
        jPanel1.add(txtConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 540, 50));

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 30, 100));

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Confirm Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 370, 100));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 540, 50));

        jLabel11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 300, 100));

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 30, 100));

        buttonGroup1.add(JrbFemale);
        JrbFemale.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
        JrbFemale.setText("  Female");
        jPanel1.add(JrbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 240, 50));

        txtDOB.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    txtDOB.setCalendarPreferredSize(new java.awt.Dimension(361, 209));
    txtDOB.setNothingAllowed(false);
    txtDOB.setFormat(2);
    txtDOB.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    txtDOB.setFieldFont(new java.awt.Font("Microsoft Himalaya", java.awt.Font.PLAIN, 50));
    jPanel1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 540, 50));

    buttonGroup1.add(JrbMale);
    JrbMale.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
    JrbMale.setSelected(true);
    JrbMale.setText("  Male");
    jPanel1.add(JrbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 240, 50));

    jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 51, 153));
    jLabel9.setText(":");
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 30, 100));

    jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(0, 51, 153));
    jLabel10.setText("Gender");
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 300, 100));

    jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 51, 153));
    jLabel7.setText("Date of Birth");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 300, 100));

    jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(0, 51, 153));
    jLabel8.setText(":");
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 30, 100));

    jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 255));
    jLabel1.setText("CREATE NEW ACCOUNT");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 800, 160));

    txtUserName.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
    txtUserName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtUserNameActionPerformed(evt);
        }
    });
    txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtUserNameKeyReleased(evt);
        }
    });
    jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 540, 50));

    jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 51, 153));
    jLabel5.setText("User Name");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 260, 100));

    jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 51, 153));
    jLabel6.setText(":");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 30, 100));

    jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 51, 153));
    jLabel4.setText(":");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 30, 100));

    txtName.setFont(new java.awt.Font("Microsoft Himalaya", 0, 50)); // NOI18N
    txtName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNameActionPerformed(evt);
        }
    });
    jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 540, 50));

    jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 51, 153));
    jLabel3.setText("Full Name");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 270, 100));

    jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(204, 204, 255));
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/white transparent.png"))); // NOI18N
    jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
    jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1000));
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1880, 1020));

    lblBackgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/technology-1106438_960_720darky.jpg"))); // NOI18N
    jPanel1.add(lblBackgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
        new LogIn().setVisible(true);

    }//GEN-LAST:event_btCancelActionPerformed

    private void chxbTurmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxbTurmsActionPerformed
        if (chxbTurms.isSelected()) {
            btCreateNewAccount.setEnabled(true);
        } else {
            btCreateNewAccount.setEnabled(false);
        }
    }//GEN-LAST:event_chxbTurmsActionPerformed

    private void txtConPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPassKeyReleased
        if (!txtPass.getText().equals(txtConPass.getText())) {
            lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Delete_remove_close_exit_trash_cancel_cross.png")));
        } else {
            lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/1-33-512.png")));
        }
        lblCor.setVisible(true);

    }//GEN-LAST:event_txtConPassKeyReleased

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        txtConPass.requestFocus();
    }//GEN-LAST:event_txtPassActionPerformed

    private void btCreateNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateNewAccountActionPerformed
        try {
            int res = checkFields();
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            if (res == 0) {
                JOptionPane.showMessageDialog(this, "Passwords didn't Match....");
            } else if (res == 1) {
                JOptionPane.showMessageDialog(this, "All Fields must be Filled to Create Account....");
            } else if (res == 2) {
                JOptionPane.showMessageDialog(this, "Passwords didn't Match....");
            }else if (studentController.checkUserName(userName)) {
                JOptionPane.showMessageDialog(this, "User Name is Already Taken....");
            } else {
                Student student = new Student(stId, userName,stName, dob, gender, pass);
                boolean isWritten = studentController.writeStudent(student);

                if (isWritten) {
                    JOptionPane.showMessageDialog(this, "Account Creation Successfully....");
                    new MainForm(userName).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Account Creation Failed....");
                }
            
            }
        } catch (IOException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCreateNewAccountActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        txtName.requestFocus();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        try {
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            if (studentController.checkUserName(txtUserName.getText())) {
                lblCorUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Delete_remove_close_exit_trash_cancel_cross.png")));
            }else{
                lblCorUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/1-33-512.png")));
            }
            
            lblCorUser.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CreateNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        if (!txtPass.getText().equals(txtConPass.getText())) {
            lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Delete_remove_close_exit_trash_cancel_cross.png")));
        } else {
            lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/1-33-512.png")));
        }
        lblCor.setVisible(true);
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JrbFemale;
    private javax.swing.JRadioButton JrbMale;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCreateNewAccount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chxbTurms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackgrond;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblCorUser;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPasswordField txtConPass;
    private datechooser.beans.DateChooserCombo txtDOB;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
