/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import com.ijse.sss.connector.ServerConnector;
import com.ijse.sss.controller.ExamController;
import com.ijse.sss.controller.NoteController;
import com.ijse.sss.controller.QuestionController;
import com.ijse.sss.controller.ResultController;
import com.ijse.sss.controller.StudentController;
import com.ijse.sss.model.Exam;
import com.ijse.sss.model.Question;
import com.ijse.sss.model.Results;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEOx
 */
public class ExamForm extends javax.swing.JFrame {

    /**
     * Creates new form ExamForm
     */
    private MainForm mainForm;
    ArrayList<Exam> allExam = new ArrayList<>();

    public ExamForm(MainForm mainForm) {
        initComponents();
        this.mainForm = mainForm;
        autoDateTime();
        addModules();
        getAllExams();
        cbType.setSelectedItem("To be Held");
    }

    private void autoDateTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    Date date = new Date();
                    String curTime = new SimpleDateFormat("hh:mm aa").format(time);
                    String curDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
                    lblTime.setText(curTime);
                    lblDate.setText(curDate);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void addModules() {
        try {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
            ArrayList<String> modules = questionController.getAllQuestionModules();
            txtModule.addItem("All Modules");
            for (String module : modules) {
                txtModule.addItem(module);
            }

        } catch (RemoteException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getAllExams() {
        try {
            ExamController examController = ServerConnector.getServerConnector().getExamController();
            allExam = examController.getAllExam();
        } catch (IOException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cbType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbHours1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbMinutes1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModule = new javax.swing.JComboBox<>();
        lblQEDesc4 = new javax.swing.JLabel();
        lblQEDesc5 = new javax.swing.JLabel();
        lblQEDesc6 = new javax.swing.JLabel();
        lblQEDesc3 = new javax.swing.JLabel();
        lblQEDesc2 = new javax.swing.JLabel();
        btCreate1 = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        lblQEDesc1 = new javax.swing.JLabel();
        btBackToHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SCHEDULED EXAM");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Exam Name", "Module", "Date", "Time", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/start.jpg"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Exams", "To be Held", "Past Exams" }));
        cbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTypeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 900, 820));

        jPanel1.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUICH EXAM");

        jLabel19.setFont(new java.awt.Font("Microsoft Himalaya", 1, 55)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Duration");

        jLabel20.setFont(new java.awt.Font("Microsoft Himalaya", 1, 55)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");

        cbHours1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 40)); // NOI18N
        cbHours1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbHours1.setSelectedItem("00");
        cbHours1.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hours");

        cbMinutes1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 40)); // NOI18N
        cbMinutes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel22.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Minutes");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/cancelSmall.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/createSmall.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Microsoft Himalaya", 1, 55)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Questions");

        jLabel24.setFont(new java.awt.Font("Microsoft Himalaya", 1, 55)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");

        jSpinner1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 40)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Module Name");

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");

        txtModule.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtModule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtModuleItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cbMinutes1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbMinutes1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(58, 58, 58))
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 930, 560));

        lblQEDesc4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc4.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc4.setText("Face Exams that Created by Teacher");
        jPanel7.add(lblQEDesc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 610, 70));

        lblQEDesc5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc5.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc5.setText("and");
        jPanel7.add(lblQEDesc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 80, 70));

        lblQEDesc6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc6.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc6.setText("Gain Your Rank");
        jPanel7.add(lblQEDesc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 770, 270, 70));

        lblQEDesc3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc3.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc3.setText("and");
        jPanel7.add(lblQEDesc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 720, 80, 70));

        lblQEDesc2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc2.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc2.setText("Measure Your Own Knowladge....");
        jPanel7.add(lblQEDesc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 770, 560, 70));

        btCreate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/quickExam.jpg"))); // NOI18N
        btCreate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCreate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCreate1MouseExited(evt);
            }
        });
        btCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreate1ActionPerformed(evt);
            }
        });
        jPanel7.add(btCreate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 270, 390, 340));

        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/scheduledExam.jpg"))); // NOI18N
        btCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCreateMouseExited(evt);
            }
        });
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        jPanel7.add(btCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 390, 340));

        lblQEDesc1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 50)); // NOI18N
        lblQEDesc1.setForeground(new java.awt.Color(255, 255, 255));
        lblQEDesc1.setText("Create a Practice Exam for Your needs.... ");
        jPanel7.add(lblQEDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 670, 700, 70));

        btBackToHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/btBackToHome.jpg"))); // NOI18N
        btBackToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBackToHomeMousePressed(evt);
            }
        });
        btBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackToHomeActionPerformed(evt);
            }
        });
        jPanel7.add(btBackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 960, 290, 60));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXAM");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 340, 90));

        lblTime.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("08:00");
        jPanel7.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 50, 330, 90));

        lblDate.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("08:00");
        jPanel7.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 120, 310, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 900, 820));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 950, 820));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 900, 820));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 950, 820));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/white transparent.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1000));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1880, 1020));

        lblBackgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/technology-1106438_960_720darky.jpg"))); // NOI18N
        jPanel7.add(lblBackgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBackToHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackToHomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBackToHomeMousePressed

    private void btBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackToHomeActionPerformed
        mainForm.show();
        this.dispose();
    }//GEN-LAST:event_btBackToHomeActionPerformed

    private void btCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateMouseEntered
        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/scheduledExamSel.jpg")));
    }//GEN-LAST:event_btCreateMouseEntered

    private void btCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateMouseExited
        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/scheduledExam.jpg")));
    }//GEN-LAST:event_btCreateMouseExited

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        btCreate.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btCreateActionPerformed

    private void btCreate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreate1MouseEntered
        btCreate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/quickExamSel.jpg")));
    }//GEN-LAST:event_btCreate1MouseEntered

    private void btCreate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreate1MouseExited
        btCreate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/quickExam.jpg")));
    }//GEN-LAST:event_btCreate1MouseExited

    private void btCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreate1ActionPerformed
        btCreate1.setVisible(false);
        lblQEDesc1.setVisible(false);
        lblQEDesc2.setVisible(false);
        lblQEDesc3.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_btCreate1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel1.setVisible(false);
        btBackToHome.setVisible(true);
        btCreate1.setVisible(true);
        lblQEDesc1.setVisible(true);
        lblQEDesc2.setVisible(true);
        lblQEDesc3.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            String module = (String) txtModule.getSelectedItem();
            int durationH = Integer.parseInt((String) cbHours1.getSelectedItem());
            int durationM = Integer.parseInt((String) cbMinutes1.getSelectedItem());
            int noOfQ = (int) jSpinner1.getValue();
            QuestionController questionController = ServerConnector.getServerConnector().getQuestionController();
            ArrayList<Question> readQuestionQtyModel = questionController.readQuestionQtyModel(noOfQ, module);
            if (!readQuestionQtyModel.isEmpty()) {
                new ExaminationForm(mainForm, module, durationH, durationM, noOfQ).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No enough nuber of Questions....");
            }

        } catch (IOException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged

    }//GEN-LAST:event_jSpinner1StateChanged

    private void txtModuleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtModuleItemStateChanged

    }//GEN-LAST:event_txtModuleItemStateChanged

    private void cbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTypeItemStateChanged
        String type = (String) cbType.getSelectedItem();
        ArrayList<Object[]> showExams = new ArrayList<>();
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable2.getModel();
        defaultTableModel.setRowCount(0);

        if (type.equalsIgnoreCase("All Exams")) {
            showExams = showExams("All Exams");
        } else if (type.equalsIgnoreCase("To be Held")) {
            showExams = showExams("To be Held");
        } else {
            showExams = showExams("Past Exams");
        }

        for (Object[] showExam : showExams) {
            defaultTableModel.addRow(showExam);
        }

    }//GEN-LAST:event_cbTypeItemStateChanged

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String selectedEid = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
            StudentController studentController = ServerConnector.getServerConnector().getStudentController();
            String stId = studentController.searchStudent(mainForm.getTitle()).getStId();
            ResultController resultController = ServerConnector.getServerConnector().getResultController();
            Results studentResult = resultController.searchStudentResults(selectedEid, stId);
            if (studentResult == null) {
                boolean isCorrect = false;
                Exam selectedExam = null;
                String examCode = JOptionPane.showInputDialog("Input Exam code for this Exam....");
                for (Exam exam : allExam) {
                    if (exam.getEid().equalsIgnoreCase(selectedEid) && exam.getExamCode().equals(examCode)) {
                        isCorrect = true;
                        selectedExam = exam;
                    }
                }
                if (isCorrect) {
                    new ExaminationForm(mainForm, selectedExam).setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Exam Code is Incorrect....");
                }
            } else {
                JOptionPane.showMessageDialog(this, "This Student already participate this Exam....");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackToHome;
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btCreate1;
    private javax.swing.JComboBox<String> cbHours1;
    private javax.swing.JComboBox<String> cbMinutes1;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBackgrond;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblQEDesc1;
    private javax.swing.JLabel lblQEDesc2;
    private javax.swing.JLabel lblQEDesc3;
    private javax.swing.JLabel lblQEDesc4;
    private javax.swing.JLabel lblQEDesc5;
    private javax.swing.JLabel lblQEDesc6;
    private javax.swing.JLabel lblTime;
    private javax.swing.JComboBox<String> txtModule;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Object[]> showExams(String type) {
        ArrayList<Object[]> rowList = new ArrayList<>();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (type.equalsIgnoreCase("All Exams")) {
            for (Exam exam : allExam) {
                String modules = "";
                for (int i = 0; i < exam.getModules().length; i++) {
                    modules += exam.getModules()[i] + ",";
                }
                modules = modules + "\b";
                Object[] row = {exam.getEid(), exam.getExamName(), modules, exam.getDate(), exam.getTime(), exam.getDuration()};
                rowList.add(row);
            }
        } else if (type.equalsIgnoreCase("To be Held")) {
            try {
                Date curDate = dateFormat.parse(lblDate.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("MMM dd,yyyy");
                for (Exam exam : allExam) {
                    Date examDate = sdf.parse(exam.getDate());
                    long diff = examDate.getTime() - curDate.getTime();
                    int diffDays = (int) (diff / (24 * 60 * 60 * 1000));

                    if (diffDays >= 0) {
                        String modules = "";
                        for (int i = 0; i < exam.getModules().length; i++) {
                            modules += exam.getModules()[i] + ",";
                        }
                        modules = modules + "\b";
                        Object[] row = {exam.getEid(), exam.getExamName(), modules, exam.getDate(), exam.getTime(), exam.getDuration()};
                        rowList.add(row);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Date curDate = dateFormat.parse(lblDate.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("MMM dd,yyyy");
                for (Exam exam : allExam) {
                    Date examDate = sdf.parse(exam.getDate());
                    long diff = examDate.getTime() - curDate.getTime();
                    int diffDays = (int) (diff / (24 * 60 * 60 * 1000));

                    if (diffDays < 0) {
                        String modules = "";
                        for (int i = 0; i < exam.getModules().length; i++) {
                            modules += exam.getModules()[i] + ",";
                        }
                        modules = modules + "\b";
                        Object[] row = {exam.getEid(), exam.getExamName(), modules, exam.getDate(), exam.getTime(), exam.getDuration()};
                        rowList.add(row);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return rowList;
    }
}
