/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import com.ijse.sss.connector.ServerConnector;
import com.ijse.sss.controller.StudentController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.ijse.sss.observer.StudentObserverImpl;
import javax.swing.DefaultListModel;

/**
 *
 * @author NEOx
 */
public class MainForm extends javax.swing.JFrame {

    private StudentObserverImpl studentObserverImpl;
    private StudentController studentController;
    DefaultListModel<String> defaultListModel = new DefaultListModel<>();

    public MainForm(String userName) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        autoDateTime();
        setTitle(userName);
        txtUserName.setText(userName);
        addToObserverList();
        setVisible(true);
        lstNotification.setModel(defaultListModel);
    }

    private void addToObserverList() {
        try {
            this.studentController = ServerConnector.getServerConnector().getStudentController();
            studentObserverImpl = new StudentObserverImpl(this);
            studentController.addStudentObserver(studentObserverImpl);

        } catch (RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form MainForm
     */
    private void autoDateTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date time = new Date();
                    Date date = new Date();
                    String curTime = new SimpleDateFormat("hh:mm aa").format(time);
                    String curDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
                    lblTime.setText(curTime);
                    lblDate.setText(curDate);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMyNotes2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstNotification = new javax.swing.JList<>();
        btExams1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        btNotes = new javax.swing.JButton();
        btExams = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMyNotes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Mynotes.jpg"))); // NOI18N
        btMyNotes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMyNotes2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMyNotes2MouseExited(evt);
            }
        });
        btMyNotes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMyNotes2ActionPerformed(evt);
            }
        });
        jPanel1.add(btMyNotes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, 390, 340));

        lstNotification.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        lstNotification.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNotificationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstNotification);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 500, 730));

        btExams1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/myAccount.jpg"))); // NOI18N
        btExams1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExams1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExams1MouseExited(evt);
            }
        });
        btExams1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExams1ActionPerformed(evt);
            }
        });
        jPanel1.add(btExams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 660, 390, 340));

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 3, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 490, 80));

        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/logout.jpg"))); // NOI18N
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLogoutMouseExited(evt);
            }
        });
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, 70));

        btNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/notes.jpg"))); // NOI18N
        btNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNotesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNotesMouseExited(evt);
            }
        });
        btNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNotesActionPerformed(evt);
            }
        });
        jPanel1.add(btNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 390, 340));

        btExams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Exams.jpg"))); // NOI18N
        btExams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExamsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExamsMouseExited(evt);
            }
        });
        btExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExamsActionPerformed(evt);
            }
        });
        jPanel1.add(btExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 280, 390, 340));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 1310, 820));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 1310, 820));

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 3, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 4));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 520, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 3, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOTIFICATIONS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 370, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 540, 820));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 540, 820));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 220, 90));

        txtUserName.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setText("ssssss");
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 540, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/user-xxl.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 4));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 100));

        lblTime.setFont(new java.awt.Font("Microsoft Himalaya", 1, 100)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("08:00");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 50, 330, 90));

        lblDate.setFont(new java.awt.Font("Microsoft Himalaya", 1, 80)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("08:00");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 120, 310, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/blackTransparent.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1860, 170));

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/white transparent.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1000));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1880, 1020));

        lblBackgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/technology-1106438_960_720darky.jpg"))); // NOI18N
        jPanel1.add(lblBackgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNotesMouseEntered
        btNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/notesSel.jpg")));
    }//GEN-LAST:event_btNotesMouseEntered

    private void btNotesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNotesMouseExited
        btNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/notes.jpg")));
    }//GEN-LAST:event_btNotesMouseExited

    private void btExamsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExamsMouseEntered
        btExams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/ExamsSel.jpg")));
    }//GEN-LAST:event_btExamsMouseEntered

    private void btExamsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExamsMouseExited
        btExams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Exams.jpg")));
    }//GEN-LAST:event_btExamsMouseExited

    private void btLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutMouseEntered

    private void btLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutMouseExited

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Logout..?");

        if (res == 0) {
            try {
                studentController.removeStudentObserver(this.studentObserverImpl);
                new LogIn().setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNotesActionPerformed
        new NotesFrame(this).setVisible(true);
        this.hide();


    }//GEN-LAST:event_btNotesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Logout..?");
        if (res == 0) {
            try {
                studentController.removeStudentObserver(this.studentObserverImpl);
                new LogIn().setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void btExams1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExams1MouseEntered
        btExams1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/myAccountSel.jpg")));
    }//GEN-LAST:event_btExams1MouseEntered

    private void btExams1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExams1MouseExited
        btExams1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/myAccount.jpg")));
    }//GEN-LAST:event_btExams1MouseExited

    private void btExams1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExams1ActionPerformed
        new MyAccount(this, this.getTitle()).setVisible(true);
        this.hide();
    }//GEN-LAST:event_btExams1ActionPerformed

    private void lstNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNotificationMouseClicked

    }//GEN-LAST:event_lstNotificationMouseClicked

    private void btMyNotes2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMyNotes2MouseEntered
        btMyNotes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/MynotesSel.jpg")));
    }//GEN-LAST:event_btMyNotes2MouseEntered

    private void btMyNotes2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMyNotes2MouseExited
        btMyNotes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Mynotes.jpg")));
    }//GEN-LAST:event_btMyNotes2MouseExited

    private void btMyNotes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMyNotes2ActionPerformed
        new MyNotes(this).setVisible(true);
        this.hide();
    }//GEN-LAST:event_btMyNotes2ActionPerformed

    private void btExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExamsActionPerformed
        new ExamForm(this).setVisible(true);
        this.hide();
    }//GEN-LAST:event_btExamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExams;
    private javax.swing.JButton btExams1;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btMyNotes2;
    private javax.swing.JButton btNotes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackgrond;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    public static javax.swing.JList<String> lstNotification;
    public static javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables

    public void setMessage(String msg) {
        MessegeFrame messegeFrame = new MessegeFrame();
        messegeFrame.txtMsg.setText(msg);
        messegeFrame.setVisible(true);
        defaultListModel.addElement(msg);
    }
}
