/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sss.view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NEOx
 */
public class StartUp extends javax.swing.JFrame {

    /**
     * Creates new form StartUp
     */
    public StartUp() {
        initComponents();
        setProgressbar();
        setLabelText();
    }
    
    private void setLabelText(){
        new Thread() {
            @Override
            public void run() {
                try {
                    while (true) {
                        txtLable.setText("");
                        Thread.sleep(20);
                    }
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
    }
    
    private void setProgressbar() {
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 101; i++) {
                        barLoad.setValue(i);
                        Thread.sleep(20);
                    }
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLable = new javax.swing.JLabel();
        barLoad = new javax.swing.JProgressBar();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLable.setFont(new java.awt.Font("Giddyup Std", 3, 100)); // NOI18N
        txtLable.setForeground(new java.awt.Color(51, 51, 51));
        txtLable.setText("The Way of Success");
        jPanel1.add(txtLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 680, 110));

        barLoad.setForeground(new java.awt.Color(0, 0, 204));
        barLoad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barLoad.setString("LOADING");
        barLoad.setStringPainted(true);
        barLoad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barLoadStateChanged(evt);
            }
        });
        jPanel1.add(barLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 820, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/sss/images/Flower-Book.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barLoadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barLoadStateChanged
        if (barLoad.getValue() == 100) {
            this.dispose();
            new LogIn().setVisible(true);
        }
    }//GEN-LAST:event_barLoadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barLoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel txtLable;
    // End of variables declaration//GEN-END:variables
}
